
[Bot]
  DisplayName = "botik"
  Enabled = false
  XUID = ""

[Connection]
  ProxyAddress = "127.0.0.1:19134"
  RemoteAddress = "127.0.0.1:19132"

[Rcon]
  Enabled = false
  Password = "948561"
  Port = 19130

[Server]
  DisableXboxAuth = false
  Ops = ["PersonalSpark46"]
  ViewDistance = 10
  Whitelist = true

[WorldBorder]
  Enabled = true
  MaxX = 5000
  MaxZ = 5000
  MinX = -5000
  MinZ = -5000
